version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
  backend:
    build:
      context: .
      dockerfile: Dockfile
    container_name: app-backend
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    environment:
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      DYNAMODB_REGION: "localhost"
      DYNAMODB_HOST: "http://dynamodb-local:8000"